### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by AngryWarlock** [jordsta95/hoi4-national-focus-maker#5] opened 2018-02-06 16:55 UTC
Is the export function broken? I just get an empty focus tree, and the file doesn't seem to contain the tree when I export.

**Comment by AngryWarlock** [comment] 2018-02-06 17:12
Now I just get one focus - the other ones do not show up. Am I doing something wrong?

**Comment by jordsta95** [comment] 2018-02-06 19:48
It is possible the tool has exported everything, but there is an error in the code generated - this has been noted a few times, especially when adding factories to states (for example). 

If you run the game with the debug launch parameters in Steam, it will tell you where the error is. If you're not sure what to make of the error log, send it my way and I'll tell you how to fix it

**Comment by AngryWarlock** [comment] 2018-02-07 17:01
Thanks for the quick reply; there is definitely something going on... Every time I export I get a different result, as you can see in the screenshot it is better, but still pretty broken this time around,

![editor](https://user-images.githubusercontent.com/36202612/35929854-c4801232-0c30-11e8-9708-0c83ffefc5f1.JPG)
![in-game](https://user-images.githubusercontent.com/36202612/35929858-c58c328c-0c30-11e8-98fa-4bbb5ba5590a.JPG)
[italia.txt](https://github.com/jordsta95/hoi4-national-focus-maker/files/1704010/italia.txt)

**Comment by jordsta95** [comment] 2018-02-07 17:56
Looks like Caesar once More requires both War Council and Undermine the Consula?

If that's the case, you need to move it down one. HOI4 is a little weird about how it draws lines when the prerequisite is on the same line (or above)

**Comment by AngryWarlock** [comment] 2018-02-07 19:25
My last example probably wasn't very clear - here is a better one.
![editortest](https://user-images.githubusercontent.com/36202612/35936891-e6318974-0c44-11e8-8ada-11e46066e7eb.JPG)
![in-gametest](https://user-images.githubusercontent.com/36202612/35936892-e72169bc-0c44-11e8-847e-1765b741223d.JPG)
[error.log](https://github.com/jordsta95/hoi4-national-focus-maker/files/1704445/error.log)

A lot more problems with this one; as you can see, only the second lines shows up.

**Comment by jordsta95** [comment] 2018-02-07 19:42
That's because it's only exporting those 2. That I can't explain...

I'm going to assume you're creating your own focus tree for Italy? If you have imported focuses from the Italian focus tree, you may find you need to update the prerequites/mutually exclusives, as the IDs the tool creates are different to the ones the default focus tree uses to ensure they don't conflict.

**Comment by AngryWarlock** [comment] 2018-02-07 22:23
That's very odd. I didn't import anything from the Italian tree, and I got the same result on an other computer. Could it have something to do with the browser? Which one do you recommend?

**Comment by jordsta95** [comment] 2018-02-08 18:19
Chrome/Edge/Internet Explorer/Opera (or any other Chromium-based browser)

I don't use a Mac, so I can't really test Safari that well, and Firefox should work, but I've had reports of bugs with it before (which should be fixed).

If you haven't used the Italian focus tree, then something is going seriously wrong with your game, as it was giving errors to do with items in the vanilla Italy focus tree

**Comment by xDangerRanger** [comment] 2018-02-10 11:42
I have "kinda" the same problem.
So.
I was exporting the focus tree like normal, everything worked fine the last 2 times I exported a focus tree.
But then I added some new focuses (all tested before) and...well...it exported it...buuuut the focus tree looks...problematic
The focus tree with your tool (website)
![nftree](https://user-images.githubusercontent.com/36329457/36061761-2b0bfd88-0e5f-11e8-8740-f51c4611dc68.PNG)
Aaaaaaaand the exported focus tree
![prob1](https://user-images.githubusercontent.com/36329457/36061766-4973dc00-0e5f-11e8-8218-8a71f09641ff.PNG)

So as you can see, there might be a problem.
Either the tool won't export focus trees rapidly (10 min time period) for testing purpose, ooooor...yeah...idk...

**Comment by jordsta95** [comment] 2018-02-10 17:13
That shouldn't be an issue (times) as it is all done on the fly.

I have recently added a few methods to check for common errors like these, along with the information required when reporting (as looking though the website's code isn't ideal), if you would be so kind as to try exporting your focus tree again, that would be great!

If the tool fails to loop through your focuses before sending them to the server to add to the file (which is what I assume the issue is) then you should get an alert telling you the information I need.
If it's failing to be processed by the server, then you should get a different message.

**Comment by xDangerRanger** [comment] 2018-02-10 17:26
Well, sorry to say that, but...it's the same.
No errors, no nothing.
It just exports the files, but without the focus tree aka just an empty file.
I'll clean my browser cache...you never know

**Comment by jordsta95** [comment] 2018-02-10 19:04
I'm going to assume clearing cache didn't work?

**Comment by xDangerRanger** [comment] 2018-02-11 09:06
Nope.
Also cleaned the website's stored data and reloaded it, but it didn't work.
Weird.

**Comment by jordsta95** [comment] 2018-02-11 10:32
Hmm, very strange. What browser (and version, if you know it) are you using?

**Comment by xDangerRanger** [comment] 2018-02-11 10:51
Uhm....chrome v64.0.3282.140 64bit

**Comment by jordsta95** [comment] 2018-02-11 10:54
Could you open up your console (F12 on on Windows/Linux, right-click inspect element on Max - don't know the keybind) and put the following, go to the console tab and note any errors you see, and also paste this there, and tell me what the result is (ensuring you have actually created a focus):

$('.all-info').length;

**Comment by xDangerRanger** [comment] 2018-02-11 16:29
Length-info: 3

After php export script console log: 16    script.js?v=1.1021:537 

(there's a console.log for reasons)

Pictures:
![nftree](https://user-images.githubusercontent.com/36329457/36075558-edede054-0f50-11e8-84de-8c240f2f8622.PNG)
Console:
![prob2](https://user-images.githubusercontent.com/36329457/36075560-fa19d6f8-0f50-11e8-981b-25464ae04563.PNG)
Script:
![prob3](https://user-images.githubusercontent.com/36329457/36075565-094481e6-0f51-11e8-8e48-8124b6b2139f.PNG)

**Comment by jordsta95** [comment] 2018-02-11 18:22
Info length of 3, OK, that's good, so it's finding your focus' info.

I forgot to remove that console log >_<

As for why it's not exporting,I think I've found the issue why. Just going to see if I can fix it now.

The tool works by encoding all focuses to a JSON before passing them to the server to handle, so there's less info to pass... But it appears that the JSON isn't being formed correctly

**Comment by jordsta95** [comment] 2018-02-11 18:31
My above assumption was incorrect, but I have just uploaded the fix now 😄

**Comment by xDangerRanger** [comment] 2018-02-12 14:46
Oh okey.
Well, thank you for your time, the tool, the fix and everything!
[Insert thumbs_up.gif]

**Comment by jordsta95** [comment] 2018-02-12 18:03
Is this working as you expect now?

If so, with the error logging I have added, both of these issues should now be resolved

**Comment by xDangerRanger** [comment] 2018-02-13 09:29
For me it's working fine...even tho it copies some focuses 2 times or so but that isn't a problem :D

**Comment by xDangerRanger** [comment] 2018-03-02 17:11
Yeah uuuuuuuuuuuuuh something new happened.
So I was trying to export a new focus I made...and this showed up:
![err01](https://user-images.githubusercontent.com/36329457/36911769-e0d3f748-1e44-11e8-8a4c-021dfcc4cd08.PNG)

And this error is shown:
![err02](https://user-images.githubusercontent.com/36329457/36911800-f6874e96-1e44-11e8-9f8c-e0dead5c56c6.PNG)

Idk if java had an update or something, but chrome has a problem with reading the .push part

**Comment by jordsta95** [comment] 2018-03-02 22:28
Forking's fine, it doesn't affect anything I do - it just saves the repo, as it is when you forked it, to your account ;)

Hmm, that's strange, I don't think I've changed that code for a while. I'm going to try and do a fair amount of fixes to this over the weekend, so I'll make sure to fix this too :)

**Comment by xDangerRanger** [comment] 2018-03-03 10:00
Okey :D

**Comment by jordsta95** [comment] 2018-03-03 18:13
This issue has now been fixed

I'm going to close this issue, as all issues discussed in this thread should now be fixed.

If you find any new issues, don't hesitate to open a new issue 😃

**Closed by jordsta95** 2018-03-03 18:13 UTC
